# Generated by Django 3.1.3 on 2025-04-07 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='지출 금액')),
                ('currency', models.CharField(max_length=10, verbose_name='통화')),
                ('description', models.TextField(blank=True, null=True, verbose_name='지출 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to=expenses.models.receipt_image_path, verbose_name='가격표 이미지')),
                ('manual_input', models.BooleanField(default=False, verbose_name='수동 입력 여부')),
                ('date', models.DateField(auto_now_add=True, verbose_name='지출 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
