# Generated by Django 4.2.20 on 2025-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_category_expense_is_scan_result_expense_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', '식비'), ('TRANSPORT', '교통'), ('SHOPPING', '쇼핑'), ('ETC', '기타')], default='OTHER', max_length=20, verbose_name='카테고리'),
        ),
    ]
