# Generated by Django 4.2.20 on 2025-06-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_trip_options_trip_total_wallet_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
        ),
    ]
