# Generated by Django 4.2.20 on 2025-06-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_remove_wallet_exchange_rate_trip_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='converted_total_krw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
