# Generated by Django 4.2.20 on 2025-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_wallet_converted_total_krw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='converted_total_krw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
