# Generated by Django 4.2.20 on 2025-06-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_wallet_converted_total_krw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='exchange_rate_to_krw',
        ),
    ]
