# Generated by Django 4.2.20 on 2025-06-04 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_trip_exchange_rate_to_krw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.AddField(
            model_name='expense',
            name='currency_code',
            field=models.CharField(default='KRW', max_length=10, verbose_name='통화 코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='denominations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='converted_total_krw',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15),
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='currency_unit',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='quantity',
        ),
    ]
