# Generated by Django 4.2.20 on 2025-06-04 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0011_alter_wallet_options_alter_wallet_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.CASCADE, to='expenses.trip'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'trip')},
        ),
    ]
