# Generated by Django 3.1.3 on 2025-04-07 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=scanner.models.scan_image_path)),
                ('scan_type', models.CharField(choices=[('receipt', '가격표 스캔'), ('currency', '화폐 스캔')], max_length=20)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
