# Generated by Django 4.2.20 on 2025-06-03 13:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scan_images/')),
                ('scan_type', models.CharField(blank=True, max_length=20, null=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('converted_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('wallet_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scanner_scanresult',
            },
        ),
    ]
