# Generated by Django 3.1.3 on 2025-04-07 16:33

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresult',
            old_name='result_text',
            new_name='extracted_text',
        ),
        migrations.RemoveField(
            model_name='scanresult',
            name='user',
        ),
        migrations.AddField(
            model_name='scanresult',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='converted_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='extracted_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='image',
            field=models.ImageField(upload_to=scanner.models.upload_scan_path),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='scan_type',
            field=models.CharField(choices=[('receipt', 'AI 결제 가이드'), ('currency', '글로벌 머니 스캐너')], max_length=20),
        ),
    ]
