# Generated by Django 4.2.20 on 2025-05-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20250408_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
